/*
 * Saque e Pague Transacional
 *
 * Modelo de API para transações da Saque e Pague. O parceiro interessado deve implementar as operações desejadas para que a SeP consiga se comunicar com o mesmo.
 *
 * OpenAPI spec version: 1.18.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Informações sobre a requisição de tranferência.
    /// </summary>
    [DataContract]
    public partial class InfTransferenciaReq : IEquatable<InfTransferenciaReq>
    { 
        /// <summary>
        /// Gets or Sets Origem
        /// </summary>
        [Required]
        [DataMember(Name="origem")]
        public InfTransferenciaReqOrigem Origem { get; set; }

        /// <summary>
        /// Gets or Sets Destino
        /// </summary>
        [Required]
        [DataMember(Name="destino")]
        public InfTransferenciaReqDestino Destino { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InfTransferenciaReq {\n");
            sb.Append("  Origem: ").Append(Origem).Append("\n");
            sb.Append("  Destino: ").Append(Destino).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InfTransferenciaReq)obj);
        }

        /// <summary>
        /// Returns true if InfTransferenciaReq instances are equal
        /// </summary>
        /// <param name="other">Instance of InfTransferenciaReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InfTransferenciaReq other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Origem == other.Origem ||
                    Origem != null &&
                    Origem.Equals(other.Origem)
                ) && 
                (
                    Destino == other.Destino ||
                    Destino != null &&
                    Destino.Equals(other.Destino)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Origem != null)
                    hashCode = hashCode * 59 + Origem.GetHashCode();
                    if (Destino != null)
                    hashCode = hashCode * 59 + Destino.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InfTransferenciaReq left, InfTransferenciaReq right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InfTransferenciaReq left, InfTransferenciaReq right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
